import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NavigationDesk } from "@/components/navigations/NavigationDesk";
import { NavigationTab } from "@/components/navigations/NavigationTab";
import { Navigation } from "@/components/navigations/Navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const background = "";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <NavigationDesk />
        <NavigationTab />
        <Navigation />
        {children}
        </body>
    </html>
  );
}
